### ISSUE TITLE
env_vars place Fn::Sub instead of value when I using Fn::Sub in env_vars

### ISSUE THREAD

**Issue by dbaloyverse** [theonestack/hl-component-ecs-schedule-runtasks#2]
When I use Fn::Sub inside env_vars - I get Fn::Sub in the compiled schema instead of real value from env vars
```yaml
run_tasks:
  lowwarescountnotify:
    container: dataserver
    task_definition: dataserver
    env_vars:
      LOG_GROUP:
        Fn::Sub: ${EnvironmentName}-dataserver-scheduled-tasks-lowstock
      USE_AWS_LOGGER: true
    command:
      - /run.sh
      - com.loyverse.dataserver.service.schedulers.LowWaresCountNotifySchedulerKt
    schedule: cron(0 * * * ? *)
```

Compiled schema:

```yaml
 lowwarescountnotifySchedule:
    Type: AWS::Events::Rule
    Properties:
      Name:
        Fn::Sub: "${EnvironmentName}-lowwarescountnotify-schedule"
      Description:
        Fn::Sub: "${EnvironmentName} lowwarescountnotify schedule"
      ScheduleExpression: cron(0 * * * ? *)
      State:
        Ref: scheduledtasksState
      Targets:
      - Id: lowwarescountnotify
        Arn:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-ecs-EcsClusterArn"
        RoleArn:
          Fn::GetAtt:
          - EventBridgeInvokeRole
          - Arn
        EcsParameters:
          TaskDefinitionArn:
            Ref: Task
          TaskCount: 1
          LaunchType: FARGATE
          NetworkConfiguration:
            AwsVpcConfiguration:
              Subnets:
                Fn::Split:
                - ","
                - Fn::ImportValue:
                    Fn::Sub: "${EnvironmentName}-vpc-ComputeSubnets"
              SecurityGroups:
              - Ref: SecurityGroup
              AssignPublicIp: DISABLED
        Input: '{"containerOverrides":[{"name":"dataserver","command":["/run.sh","com.loyverse.dataserver.service.schedulers.LowWaresCountNotifySchedulerKt"],"environment":{"LOG_GROUP":{"Fn::Sub":"${EnvironmentName}-dataserver-scheduled-tasks-lowstock"},"USE_AWS_LOGGER":true}}]}'
```

I expect that `"LOG_GROUP":{"Fn::Sub":"${EnvironmentName}-dataserver-scheduled-tasks-lowstock"}` should be replaced with `"LOG_GROUP":{"prod-dataserver-scheduled-tasks-lowstock"}`

Please add support to use substitution in containerOverrides if possible.
